// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Uygtk5Dw62jy_HS2phGUTrkZ1v03fps',
    appId: '1:631618516414:web:0f3abb411e2a90bd3475ef',
    messagingSenderId: '631618516414',
    projectId: 'taresas-prueba',
    authDomain: 'taresas-prueba.firebaseapp.com',
    storageBucket: 'taresas-prueba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaxpyU4v4dFeyIjJg2iauBJo6CoeTkukc',
    appId: '1:631618516414:android:256eaf6924f3d01d3475ef',
    messagingSenderId: '631618516414',
    projectId: 'taresas-prueba',
    storageBucket: 'taresas-prueba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-SZ-E1lA1Hsb8ouDT1YC3oo7FFqhCkNc',
    appId: '1:631618516414:ios:0ea0026983e449983475ef',
    messagingSenderId: '631618516414',
    projectId: 'taresas-prueba',
    storageBucket: 'taresas-prueba.firebasestorage.app',
    iosBundleId: 'com.example.taskTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-SZ-E1lA1Hsb8ouDT1YC3oo7FFqhCkNc',
    appId: '1:631618516414:ios:0ea0026983e449983475ef',
    messagingSenderId: '631618516414',
    projectId: 'taresas-prueba',
    storageBucket: 'taresas-prueba.firebasestorage.app',
    iosBundleId: 'com.example.taskTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Uygtk5Dw62jy_HS2phGUTrkZ1v03fps',
    appId: '1:631618516414:web:67e84e528d82de663475ef',
    messagingSenderId: '631618516414',
    projectId: 'taresas-prueba',
    authDomain: 'taresas-prueba.firebaseapp.com',
    storageBucket: 'taresas-prueba.firebasestorage.app',
  );
}
